### ISSUE TITLE
Handling cases where there are multiple files/pipes

### ISSUE THREAD

**Issue by necrolyte2** [VDBWRAIR/bioframework#3]
In the mini pipeline here
```
mkfifo pipe1
mkfifo pipe2
cutadapt -q 25,25 -o pipe1 -p pipe2 read1.fastq read2.fastq &
bwa mem -v 9 pipe1 pipe2
```
The pipeline will hang just after bwa starts because cutadapt writes sequentially first to pipe1 then when finished to pipe2.
Since cutadapt is non-parallel in its writes, it is trying to wait until it completes writing to the ``-o`` option before writing to ``-p``. Thus the entire pipeline hangs

I have patched cutadapt and made the writes occur in separate threads to confirm this. The parallel thread version is much slower(The old GIL issue most likely), but the pipeline does complete now

**Comment by averagehat** [comment]
could you use multiprocessing instead of threads?

**Comment by necrolyte2** [comment]
Ya, but the implementation becomes more difficult at that point since you are then having to fork the process and setup pipes to communicate between them.... I'm going to investigate doing round-robin chunk writing.

**Comment by necrolyte2** [comment]
There is a bit of discussion already about threading/multiprocessing for cutadapt
marcelm/cutadapt#148

**Comment by averagehat** [comment]
This has been fixed upstream in cutadapt.
